# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MaratonIME Winter School
email: maratona@ime.usp.br
description: USP 2017 ICPC Winter School.
baseurl: "/~maratona/winter17" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
